spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVER:credit-keycloak}:${KEYCLOAK_PORT:8080}/realms/credit-realm

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://admin-eureka:admin@credit-eureka:8761/eureka/}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.cardgenerator: INFO 